### PR TITLE
Fix conditional compilation in generated C++ code

### LINKED ISSUE #299: Fix conditional compilation in generated C++ code
Guards for functions that include `|| BUILD_UT` can cause compilation issues if the functions depend on other guards being defined. For example, this function:

https://github.com/fprime-community/fpp/blob/00c54e0b78357514cea9e27d6e25f50f222324f2/compiler/tools/fpp-to-cpp/test/array/AArrayAc.ref.cpp#L177-L201

will fail to compile if  `BUILD_UT` is on and `FW_ARRAY_TO_STRING` is off because `FW_ARRAY_TO_STRING_BUFFER_SIZE` is guarded by `FW_ARRAY_TO_STRING` (see https://github.com/nasa/fprime/blob/92c9f0712358ee34789c69a4cdc013f17748ad86/config/FpConfig.h#L311-L315).

To fix this, `|| BUILD_UT` should be removed from these guards.

### PR DESCRIPTION
**Pull request by tiffany1618**
Closes #299.

### CODE REVIEW

**Comment by bocchino** [comment]
Before merging this PR, we need to remove all the instances of `|| BUILD_UT` and `&& BUILD_UT`.

**Comment by bocchino** [comment]
Looks good! We should just confirm that it works with F Prime.

**Comment by tiffany1618** [comment]
This passes the F Prime unit tests and the F Prime FPP tests.

**Review by bocchino — APPROVED** [review]
Looks good!

**Pull request merged**
