### PR TITLE
Update FPP version stamp

### PR DESCRIPTION
**Pull request by bocchino**
Update the version to v2.0.2.

### CODE REVIEW

**Comment by bocchino** [comment]
Closed and reopened the PR to trigger the new CI checks.

**Comment by LeStarch** [comment]
Triggering new CI build!

**Comment by LeStarch** [comment]
And again, new CI!

**Comment by LeStarch** [comment]
And again, new CI!  Note: this *should* represents the last CI change.  Now just debugging this run.

**Comment by LeStarch** [comment]
Debugging fixes require close/re-open.

**Pull request merged**
