### PR TITLE
Fixing implementation include paths

### LINKED ISSUE #355: Fix Template Generation Include Paths
When generating template include paths, the relative path to the header is based on the current working directory of the execution.  However, this is inconsistent with other code generation where the include path is relative to the model file (symbol location).

This inconsistency should be fixed!

### PR DESCRIPTION
**Pull request by LeStarch**
This fixes #355!

### CODE REVIEW

**Comment by LeStarch** [comment]
@thomas-bc here is the fix for the issue we discovered!  It was not as simple as I first indicated, as we needed to:

1. Acquire the Component symbol's location (FPP model file location defining symbol)
2. Convert that to a full path
3. Strip prefixes
4. Add .hpp
5. Pass to "make include statement" function (this was done already, but on erroneous input)

**Review by bocchino — APPROVED** [review]
Looks good! I made the corresponding changes to the headers in the test implementation.

**Comment by bocchino** [comment]
I also refactored a bit to eliminate code duplication.

**Comment by bocchino** [comment]
The CI failure is due to some issue with Python packages.

**Pull request merged**
