### PR TITLE
Revise semantic checking of serial port connections

### LINKED ISSUE #183: Enforce rules concerning return types with serial ports
When a serial port is connected to a typed input port `p`, the port type of `p` should not have a return type.

- [x] Update spec
- [x] Add check to semantics
- [x] Unit test
- [x] Update User's Guide

Add the corresponding rule for a typed output port `p` and a serial input port, when the port type of `p` has a return type.

- [x] Update spec
- [x] Add check to semantics
- [x] Unit test
- [x] Update User's Guide

### PR DESCRIPTION
**Pull request by bocchino**
* Exclude the cases where a serial port is connected to a typed port, and the typed port has a return type.
* Update the spec, implementation, unit tests, and user's guide.
* Make some incidental revisions to the user's guide.

Closes #183.

### CODE REVIEW

**Comment by tiffany1618** [comment]
Should we also be excluding the case where a typed output port with a return type is connected to a serial input port?

**Comment by bocchino** [comment]
Yes, that sounds right. What happens in this case in the current implementation? Does the code even compile?

**Comment by tiffany1618** [comment]
I think the expected behavior is to have an assertion fail on a nullptr, but currently it seg faults when `FW_PORT_SERIALIZATION` is defined. Here is the code that's generated:

https://github.com/fprime-community/fpp/blob/d55f67d48c8fe01994bd1abddd47974e98ab6667/compiler/tools/fpp-to-cpp/test/port/ReturnTypePortAc.ref.cpp#L110-L115

Maybe we should remove lines 110-112 for ports with return types.

**Comment by bocchino** [comment]
> Maybe we should remove lines 110-112 for ports with return types.

Yes, that sounds right. Also, we should systematically replace `FW_ASSERT(ptr)` with `FW_ASSERT(ptr != nullptr)`. C++ does not guarantee that `nullptr == 0`.

**Comment by bocchino** [comment]
OK, I revised the PR to exclude both serial -> typed and typed -> serial.

**Review by tiffany1618 — APPROVED** [review]
Looks good!

**Pull request merged**
