### PR TITLE
Improve support for manual topology setup

### LINKED ISSUE #239: Improve support for manual topology setup
The topology code generator currently optimizes away functions that are not called by the auto-generated `setup` function -- e.g., no `loadParameters` function is generated if there are no parameters and `setup` doesn't call `loadParameters`. This causes issues when users want to write a manual `setup` function, because the setup function has to change if the functions appear and disappear. The fix is to generate empty functions and call them.

### PR DESCRIPTION
**Pull request by bocchino**
Closes #239.

### CODE REVIEW

**Comment by bocchino** [comment]
@LeStarch When you get a chance, can you look at this PR? It implements a feature that you requested.

**Review by LeStarch — APPROVED** [review]
@bocchino I read this change as the following:

Originally, we matched the body (lines of the function), if empty/nil then nothing was produced, otherwise the `Some` thing was produced (presumably with the function implementation per `ll`).

Now we are *always* setting `ll` to the result of the body match.  Nil produces a single comment line, and anything else produces the original lines. `Some` always runs but may just be passed a comment.

The effect is now a function is always produced, sometimes just a comment, otherwise the implementation. 

If this analysis is correct, then I approve this change!

**Comment by LeStarch** [comment]
@bocchino I wrote-up my understanding in the approval. If that is the gist of what is happening, then this is approved!

**Comment by bocchino** [comment]
Yes, that is correct. Thanks!

**Pull request merged**
